import { WorkerStatus } from '@constant';
import { LanguageCode } from '@types';
import { ICONS, IMAGES } from '../assets/svg';

export const DATA = {
  driverQuickAccess: [
    { id: '1', label: 'Locator', Icon: ICONS.PIN_CHECK.default },
    { id: '2', label: 'Worker Pickup', Icon: ICONS.PICK_UP.default },
    { id: '3', label: 'Stock Pickup', Icon: ICONS.PICK_UP_ONE.default },
    { id: '4', label: 'Projects', Icon: ICONS.DOC_DOLLAR.default },
    { id: '5', label: 'Manager Requests', Icon: ICONS.DOC_TIMER.default },
  ],
  workerQuickAccess: [
    { id: '1', label: 'Check-In', Icon: ICONS.PIN_CHECK.default },
    { id: '2', label: 'New Pickup', Icon: ICONS.PLUS.default },
    { id: '3', label: 'New Material', Icon: ICONS.PLUS.default },
    { id: '4', label: 'Pickup Requests', Icon: ICONS.PICK_UP.default },
    { id: '5', label: 'Material Requests', Icon: ICONS.PICK_UP_ONE.default },
    { id: '6', label: 'Projects', Icon: ICONS.DOC_DOLLAR.default },
  ],
  dashboard: [
    { id: '1', label: 'New Projects', count: '15' },
    { id: '2', label: 'Active Projects', count: '03' },
    { id: '3', label: 'Overdue Projects', count: '05' },
    { id: '4', label: 'New Stock Request', count: '11' },
    { id: '4', label: 'Pending Stock', count: '01' },
    { id: '5', label: 'Active Stock', count: '09' },
    { id: '6', label: 'New Pickup Request', count: '14' },
    { id: '7', label: 'Active Pickup', count: '33' },
    { id: '8', label: 'Pending Pickup', count: '22' },
  ],
  workerDashboard: [
    { id: '1', label: 'New Projects', count: '15' },
    { id: '2', label: 'Active Projects', count: '03' },
    { id: '3', label: 'Overdue Projects', count: '05' },
  ],
  pickupWorker: [
    {
      id: '1',
      name: 'Theresa Webb',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Pending' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    },
    {
      id: '2',
      name: 'Theresa Webb',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Pending' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    },
    {
      id: '3',
      name: 'Leslie Alexander',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Pending' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    },
    {
      id: '4',
      name: 'Annette Black',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Completed' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    },
    {
      id: '5',
      name: 'Marvin McKinney',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'In-Progress' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    },
    {
      id: '6',
      name: 'Esther Howard',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Completed' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    },
    {
      id: '7',
      name: 'Darlene Robertson',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Completed' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
    },
  ],
  workerStock: [
    {
      id: '1',
      name: 'Theresa Webb',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Pending' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
      quantity: '50 Bags',
      item: 'Cement Bags',
    },
    {
      id: '2',
      name: 'Annette Black',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Completed' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
      quantity: '1,000 Units',
      item: 'Red Bricks',
    },
    {
      id: '3',
      name: 'Theresa Webb',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Pending' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
      quantity: '1 Unit',
      item: 'Concrete Mixer',
    },
    {
      id: '4',
      name: 'Marvin McKinney',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'In-Progress' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
      quantity: '25 Panels',
      item: 'Form Panels',
    },
    {
      id: '5',
      name: 'Esther Howard',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      status: 'Completed' as WorkerStatus,
      avatar:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
      quantity: '200 Rods',
      item: 'Steel Rods',
    },
    // {
    //   id: '6',
    //   name: 'Leslie Alexander',
    //   phone: '0334-5133889',
    //   address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
    //   project: 'Dolphin site mall, Islamabad.',
    //   time: '12:30 PM',
    //   date: '4 Jun, 2025',
    //   status: 'Pending' as WorkerStatus,
    //   avatar:
    //     'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    //   quantity: '1 Unit',
    // },
    // {
    //   id: '7',
    //   name: 'Darlene Robertson',
    //   phone: '0334-5133889',
    //   address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
    //   project: 'Dolphin site mall, Islamabad.',
    //   time: '12:30 PM',
    //   date: '4 Jun, 2025',
    //   status: 'Completed' as WorkerStatus,
    //   avatar:
    //     'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
    //   quantity: '1,000 Units',
    // },
  ],
  orderStatus: [
    { label: 'Pending', value: 'Pending' },
    { label: 'In-Progress', value: 'In-Progress' },
    { label: 'Completed', value: 'Completed' },
  ],
  driverInfo: {
    name: 'John Alex',
    role: 'Driver',
    workingHours: '10:00AM - 07:00 PM',
    profileImage:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    phone: '+92 300 5199448',
    email: 'example@gmail.com',
    vehicle: {
      name: 'Hyundai 120 Nine',
      number: 'AED-345',
      status: 'Active',
      color: 'White',
      model: '2019',
      image: IMAGES.CAR,
    },
  },
  pickupStock: [
    // {
    //   id: '1',
    //   name: 'Jacob Jones',
    //   phone: '0323-4455122',
    //   address: 'G-11, Islamabad.',
    //   project: 'Residential Flats',
    //   time: '03:45 PM',
    //   date: '6 Jun, 2025',
    //   item: 'Concrete Mixers, Wheelbarrows',
    //   quantity: '3 Mixers, 5 Wheelbarrows',
    //   decisionBy: 'Civil Engineer',
    //   decisionTime: '04:00:15 PM | 25-05-2025',
    //   status: 'Pending',
    //   avatar: 'https://randomuser.me/api/portraits/men/4.jpg',
    // },
    {
      id: '2',
      name: 'Wade Warren',
      phone: '0333-1478523',
      address: 'Gulberg Greens, Islamabad.',
      project: 'Mall Extension',
      time: '11:30 AM',
      date: '7 Jun, 2025',
      item: 'Electric Drills, Extension Cords',
      quantity: '4 Drills, 10 Cords',
      decisionBy: 'Electrical Lead',
      decisionTime: '11:45:00 AM | 26-05-2025',
      status: 'Pending',
      avatar: 'https://randomuser.me/api/portraits/men/6.jpg',
    },
    {
      id: '3',
      name: 'Leslie Alexander',
      phone: '0300-6549871',
      address: 'Rawalpindi Ring Road.',
      project: 'Highway Expansion Project',
      time: '05:30 PM',
      date: '10 Jun, 2025',
      item: 'Bulldozer Parts',
      quantity: 'Full Engine Set',
      decisionBy: 'Logistics Manager',
      decisionTime: '06:00:00 PM | 28-05-2025',
      status: 'Pending',
      avatar: 'https://randomuser.me/api/portraits/women/9.jpg',
    },
    {
      id: '4',
      name: 'Cameron Williamson',
      phone: '0334-5133889',
      address: 'Jinnah Avenue. Dolphin site mall, Islamabad.',
      project: 'Dolphin site mall, Islamabad.',
      time: '12:30 PM',
      date: '4 Jun, 2025',
      item: 'Hand Drills, Measuring Tapes',
      quantity: '2 Hand Drills, 5 Measuring Tapes',
      decisionBy: 'Project Manager',
      decisionTime: '12:30:46 PM | 24-05-2025',
      status: 'In-Progress',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    {
      id: '5',
      name: 'Floyd Miles',
      phone: '0311-6523488',
      address: 'I-8 Markaz, Islamabad.',
      project: 'City Mall, Islamabad.',
      time: '01:00 PM',
      date: '5 Jun, 2025',
      item: 'Wrenches, Hammers',
      quantity: '5 Wrenches, 3 Hammers',
      decisionBy: 'Site Engineer',
      decisionTime: '01:15:10 PM | 24-05-2025',
      status: 'Completed',
      avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
    },
    {
      id: '6',
      name: 'Devon Lane',
      phone: '0332-9876543',
      address: 'Blue Area, Islamabad.',
      project: 'Blue Tower Project',
      time: '02:15 PM',
      date: '6 Jun, 2025',
      item: 'Paint Buckets, Brushes',
      quantity: '10 Buckets, 20 Brushes',
      decisionBy: 'Paint Supervisor',
      decisionTime: '02:20:30 PM | 25-05-2025',
      status: 'Completed',
      avatar: 'https://randomuser.me/api/portraits/women/3.jpg',
    },
    {
      id: '7',
      name: 'Guy Hawkins',
      phone: '0345-8765432',
      address: 'F-10, Islamabad.',
      project: 'Skyline Apartments',
      time: '10:00 AM',
      date: '7 Jun, 2025',
      item: 'Cement Bags',
      quantity: '50 Bags',
      decisionBy: 'Construction Manager',
      decisionTime: '10:30:00 AM | 26-05-2025',
      status: 'Completed',
      avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    },
    {
      id: '8',
      name: 'Arlene McCoy',
      phone: '0312-7896541',
      address: 'Bahria Town, Islamabad.',
      project: 'Bahria Heights Project',
      time: '09:00 AM',
      date: '8 Jun, 2025',
      item: 'Tiles, Marble Sheets',
      quantity: '300 Tiles, 20 Marble Sheets',
      decisionBy: 'Procurement Officer',
      decisionTime: '09:15:00 AM | 27-05-2025',
      status: 'Completed',
      avatar: 'https://randomuser.me/api/portraits/women/7.jpg',
    },
    {
      id: '9',
      name: 'Theresa Webb',
      phone: '0342-9632587',
      address: 'I-9, Islamabad.',
      project: 'Corporate Plaza',
      time: '04:00 PM',
      date: '9 Jun, 2025',
      item: 'Steel Rods, Pipes',
      quantity: '100 Rods, 50 Pipes',
      decisionBy: 'Project Supervisor',
      decisionTime: '04:15:00 PM | 27-05-2025',
      status: 'In-Progress',
      avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
    },
    {
      id: '10',
      name: 'Darlene Robertson',
      phone: '0321-9513576',
      address: 'Saddar, Rawalpindi.',
      project: 'Metro Bus Extension',
      time: '07:00 PM',
      date: '10 Jun, 2025',
      item: 'Pipes, Joints',
      quantity: '200 Pipes, 300 Joints',
      decisionBy: 'Pipeline Supervisor',
      decisionTime: '07:30:00 PM | 28-05-2025',
      status: 'Completed',
      avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
    },
  ],
  checkIns: [
    {
      id: '1',
      title: 'Green Valley Residences',
      location: 'Industrial Zone, Port Qasim, Karachi.',
      dateTime: '12:30 PM | 4 Jun, 2025',
      shiftTime: '8:00 AM – 6:00 PM',
      status: 'recent',
    },
    {
      id: '2',
      title: 'Axis Business Center',
      location: 'Main Boulevard, Gulberg III, Lahore.',
      dateTime: '12:30 PM | 4 Jun, 2025',
      shiftTime: '9:00 AM – 5:00 PM',
      status: 'recent',
    },
    {
      id: '3',
      title: 'Falcon Industrial Park',
      location: 'Industrial Zone, Port Qasim, Karachi.',
      dateTime: '12:30 PM | 4 Jun, 2025',
      shiftTime: '7:30 AM – 4:30 PM',
      status: 'recent',
    },
    {
      id: '4',
      title: 'Green Valley Residences',
      location: 'Industrial Zone, Port Qasim, Karachi.',
      dateTime: '12:30 PM | 4 Jun, 2025',
      shiftTime: '8:00 AM – 6:00 PM',
      status: 'ongoing',
    },
    {
      id: '5',
      title: 'Axis Business Center',
      location: 'Main Boulevard, Gulberg III, Lahore.',
      dateTime: '12:30 PM | 4 Jun, 2025',
      shiftTime: '9:00 AM – 5:00 PM',
      status: 'ongoing',
    },
    {
      id: '6',
      title: 'Axis Business Center',
      location: 'Sector 45, Bahria Town, Islamabad.',
      shiftTime: '9:00 AM – 5:00 PM',
      checkIn: '12:30 PM • 4 Jun, 25',
      checkOut: '12:30 PM • 4 Jun, 25',
      status: 'completed',
    },
    {
      id: '7',
      title: 'Axis Business Center',
      location: 'Zone B, Eastern Bypass, Ring Road Junction, Faisalabad.',
      shiftTime: '9:00 AM – 5:00 PM',
      checkIn: '12:30 PM • 4 Jun, 25',
      checkOut: '12:30 PM • 4 Jun, 25',
      status: 'completed',
    },
  ],
  projectsData: [
    {
      id: '1',
      moduleId: '334',
      name: 'Green Valley Residences',
      location: 'Industrial Zone, Port Qasim, Karachi',
      hours: '8:00 AM – 6:00 PM',
      status: 'Completed',
      image: 'https://images.pexels.com/photos/68704/pexels-photo-68704.jpeg',
      coordinate: { latitude: 33.5651, longitude: 73.0169 },
    },
    {
      id: '2',
      moduleId: '34',
      name: 'Sunset Apartments',
      location: 'Gulshan Block 5, Karachi',
      hours: '9:00 AM – 5:00 PM',
      status: 'In-Progress',
      image: 'https://images.pexels.com/photos/68704/pexels-photo-68704.jpeg',
      coordinate: { latitude: 33.5651, longitude: 73.0169 },
    },
    {
      id: '3',
      moduleId: '505',
      name: 'Oceanview Heights',
      location: 'Clifton Phase 8, Karachi',
      hours: '7:00 AM – 7:00 PM',
      status: 'Completed',
      image: 'https://images.pexels.com/photos/68704/pexels-photo-68704.jpeg',
      coordinate: { latitude: 33.5651, longitude: 73.0169 },
    },
    {
      id: '4',
      moduleId: '044',
      name: 'Skyline Villas',
      location: 'Malir Cantt, Karachi',
      hours: '10:00 AM – 6:00 PM',
      status: 'In-Progress',
      image: 'https://images.pexels.com/photos/68704/pexels-photo-68704.jpeg',
      coordinate: { latitude: 33.5651, longitude: 73.0169 },
    },
    {
      id: '5',
      moduleId: '021',
      name: 'Palm Grove',
      location: 'Scheme 33, Karachi',
      hours: '8:30 AM – 5:30 PM',
      status: 'Completed',
      image: 'https://images.pexels.com/photos/68704/pexels-photo-68704.jpeg',
      coordinate: { latitude: 33.5651, longitude: 73.0169 },
    },
    {
      id: '6',
      moduleId: '198',
      name: 'Maple Residences',
      location: 'DHA Phase 6, Karachi',
      hours: '8:00 AM – 6:00 PM',
      status: 'In-Progress',
      image: 'https://images.pexels.com/photos/68704/pexels-photo-68704.jpeg',
      coordinate: { latitude: 33.5651, longitude: 73.0169 },
    },
    {
      id: '7',
      moduleId: '311',
      name: 'Elite Tower',
      location: 'North Nazimabad, Karachi',
      hours: '9:00 AM – 6:00 PM',
      status: 'Completed',
      image: 'https://images.pexels.com/photos/68704/pexels-photo-68704.jpeg',
      coordinate: { latitude: 33.5651, longitude: 73.0169 },
    },
    {
      id: '8',
      moduleId: '422',
      name: 'Pearl Residency',
      location: 'University Road, Karachi',
      hours: '7:30 AM – 5:30 PM',
      status: 'In-Progress',
      image: 'https://images.pexels.com/photos/68704/pexels-photo-68704.jpeg',
      coordinate: { latitude: 33.5651, longitude: 73.0169 },
    },
  ],
  projectTabs: [
    { id: 'recent', label: 'Recents' },
    { id: 'ongoing', label: 'Ongoing' },
    { id: 'completed', label: 'Completed' },
  ],
  workerPickupTabs: [
    { id: 'recent', label: 'Recents' },
    { id: 'create', label: 'Create New Request' },
  ],
  projects: [
    { label: 'Project A', value: 'project_a', location: 'Location A' },
    { label: 'Project B', value: 'project_b', location: 'Location B' },
  ],
  languageOptions: [
    { label: 'English', code: 'en_US' as LanguageCode },
    { label: 'French', code: 'fr_CA' as LanguageCode },
  ],
  stockItems: [
    {
      projectId: '1',
      name: 'Drilling Machine',
      code: 'DM-001',
      availableQty: 100,
    },
    {
      projectId: '1',
      name: 'Measuring Tape',
      code: 'MT-002',
      availableQty: 80,
    },
    {
      projectId: '2',
      name: 'Hand Grinder',
      code: 'HG-003',
      availableQty: 50,
    },
    {
      projectId: '2',
      name: 'Safety Helmet',
      code: 'SH-004',
      availableQty: 120,
    },
    {
      projectId: '1',
      name: 'Power Drill',
      code: 'PD-005',
      availableQty: 60,
    },
  ],
};
